# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1a8c32c4d1739001301216250384e7268b226b621e44b969a5f396a1b0799d4603ac3de21c2d4cf05a323feb3c28e6773ee75282724342fe557e9aad20437ab

test:
  secret_key_base: c122d11c4b79af27f995e6f364e540287fcf26b4a06a3e5c1675a8aa8cc8a70b31b481a531b1955db6926d49baa5cb60a8c2b260fe7dd66dcdf8df620ccb3640

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
